services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_AUTH_SOURCE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_vol:/data/db

volumes:
  mongo_vol:
    driver: local
