# docker-compose.yml
services:
  rag:
    image: self-reflective-rag:latest
    build:
      context: .
      dockerfile: Dockerfile
      # Assuming HF_TOKEN is needed during build, keep args
      args:
        HF_TOKEN: ${HF_TOKEN}
    container_name: rag
    restart: always
    env_file:
      - .env
    # *** CHANGE condition to service_healthy ***
    depends_on:
      mongodb:
        condition: service_healthy # Wait until mongodb reports healthy
    ports:
      - "8002:8000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_AUTH_SOURCE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_vol:/data/db
    # *** ADD healthcheck ***
    healthcheck:
      test: |
        mongosh \
          --eval 'quit(db.adminCommand("ping").ok ? 0 : 1)' \
          --host localhost \
          -u ${MONGO_USER} \
          -p ${MONGO_PASSWORD} \
          --authenticationDatabase ${MONGO_AUTH_SOURCE}
      interval: 10s # Check every 10 seconds
      timeout: 5s # Give the command 5 seconds to complete
      retries: 10 # Try 10 times before marking as unhealthy
      start_period: 30s # Give the service 30 seconds to start before checking

volumes:
  mongo_vol:
    driver: local
