services:
  orchestrator:
    image: orchestrator:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orchestrator
    restart: always
    env_file:
      - .env
    ports:
      - "8004:8004"
