services:
  kavas_db:
    image: ankane/pgvector:latest
    container_name: kavas_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: kavas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8502:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

  app:
    image: kavas_voice_service:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HF_TOKEN: ${HF_TOKEN}
    container_name: voice_recognition
    depends_on:
      kavas_db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8001:8000"
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
